source 'https://rubygems.org/'

gem 'jekyll', :git => 'git://github.com/puppetlabs/jekyll.git', :branch => 'puppetdocs'
gem 'maruku'
gem 'kramdown'
gem 'versionomy'
gem 'rack'
gem 'yard'
gem 'rdoc'
gem 'rake'
gem 'vlad'
gem 'vlad-git'
gem 'activerecord', '~>3'
gem 'ronn'
