#!/usr/bin/env ruby

# > mangle_files ./file1.html ./file2.html ./file3.html

# This script expects any number of HTML fragment files as its argument(s). It
# will mangle the content and update it in-place, destroying the previous
# content of the files.

require 'puppet_docs/sentence_segmenter'

ARGV.each do |filename|
  PuppetDocs::SentenceSegmenter.mangle_file(filename)
end

